# Generated by Django 3.1 on 2022-07-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=1000, verbose_name="Commit's Hash")),
                ('time', models.CharField(max_length=1000, verbose_name='Commit Time')),
                ('author', models.CharField(max_length=1000, verbose_name='Commit Name')),
                ('email', models.CharField(max_length=1000, verbose_name='Commit Email')),
            ],
            options={
                'db_table': 'diffs_commits',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200, unique=True, verbose_name='Project ID String')),
            ],
            options={
                'db_table': 'diffs_projects',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200, verbose_name='Release ID String')),
                ('last_commit_hash', models.CharField(max_length=1000, verbose_name="Release Last Commit's Hash")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffs.project')),
            ],
            options={
                'db_table': 'diffs_releases',
            },
        ),
        migrations.CreateModel(
            name='UnCalculateObjectChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(default='', max_length=10000)),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=1000)),
                ('hash', models.CharField(max_length=1000)),
                ('object_id', models.CharField(max_length=1000)),
                ('old_object_id', models.CharField(max_length=1000)),
                ('old_line_count', models.IntegerField(default=0)),
                ('current_line_count', models.IntegerField(default=0)),
                ('deleted_line_count', models.IntegerField(default=0)),
                ('added_line_count', models.IntegerField(default=0)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffs.commit', verbose_name='Object belongs to commit')),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diffs.release', verbose_name='Object belongs to release')),
            ],
            options={
                'db_table': 'diffs_object_change',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=1000, verbose_name="Object's location(path)")),
                ('object_id', models.CharField(max_length=200, verbose_name="Object's structure chains")),
                ('owner_info', models.JSONField(default=dict, verbose_name='Object owner json list')),
                ('old_confidence', models.FloatField(default=0, verbose_name='Last confidence')),
                ('confidence', models.FloatField(default=0, verbose_name='Current confidence')),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('parameters', models.CharField(default='', max_length=10000)),
                ('commit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diffs.commit')),
            ],
            options={
                'db_table': 'diffs_objects',
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffs.release'),
        ),
        migrations.AddConstraint(
            model_name='uncalculateobjectchange',
            constraint=models.UniqueConstraint(fields=('path', 'object_id', 'hash', 'commit', 'parameters', 'start_line', 'end_line'), name='unique_commit_object_object_Change'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='Project Contains Releases'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('path', 'object_id', 'parameters'), name='Release Contains Objects'),
        ),
        migrations.AlterIndexTogether(
            name='object',
            index_together={('object_id', 'parameters', 'path')},
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('hash', 'release'), name='Release Contains Commits'),
        ),
    ]
