# Generated by Django 3.0.8 on 2021-07-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200, unique=True, verbose_name='Project ID String')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(default='', max_length=50, verbose_name='Product Release')),
                ('commit_hash', models.CharField(max_length=100, verbose_name='Product Commit Hash')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffs.Project', verbose_name='Product Belongs to Project')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Object Name')),
                ('file_path', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100, verbose_name='Object Belongs to Owner')),
                ('commit_time', models.DateTimeField(verbose_name='commit time')),
                ('hash', models.CharField(max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('old_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffs.Project', verbose_name='Object Belongs to the Project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffs.Release', verbose_name='Object Belongs to the Product')),
            ],
        ),
    ]
